### ISSUE TITLE
ArrayWriter.h unused?

### ISSUE THREAD

**Issue by perezd** [Yakim3396/PingQoS#1]
Context: PingQoS/Source/PingQoS/Public/PingQoSWorker.h

I had to remove `#include "ArrayWriter.h"` to get this to compile. Should it be removed generally? Did I do something wrong?

**Comment by Yakim3396** [comment]
This header is not used, I deleted it in my project, but forgot to upload the changes to the GitHub.
Now I have updated the repository, everything should be fine.
